from tkinter import *
import os
import cx_Oracle as co
from tkinter import messagebox
def cancel1():
    ro.destroy()
    os.system("homescreen.py")
def sub():
    con = co.connect("scott/tiger")
    cur = con.cursor()
    fnameval = fname.get()
    lnameval = lname.get()
    mothernameval = mothername.get()
    fathernameval = fathername.get()
    mobileval = int(Mobile.get())
    emailval = email.get()
    addressval = Add.get()
    matval = int(matricagg.get())
    sensecval = int(sen_secc.get())
    coursedetval = coursedet.get()
    departval = depart.get()
    if fname.get()=='' and lname.get()=='' and fathername.get()=='' and mothername.get()=='' and Mobile.get()=='' and email.get()=='' and Add.get()=='' and matricagg.get()=='' and sen_secc.get() =='' and coursedet.get()=='' and depart.get()=='':
        messagebox.showinfo("Registration Form","Entry is Empty")
    elif fname.get()=='' or lname.get()=='' or fathername.get()=='' or mothername.get()=='' or Mobile.get()=='' or email.get()=='' or Add.get()=='' or matricagg.get()=='' or sen_secc.get() =='' or coursedet.get()=='' or depart.get()=='':
        messagebox.showinfo("Registration Form","Entry is Empty")
    else:
        cur.execute("insert into student1 values(sno_seq.nextval,:fnameval,:lnameval,:fathernameval,:mothernameval,:mobileval,:emailval,:addressval,:matval,:sensecval,:coursedetval,:departval)",{":fnameval":fnameval,":lnameval":lnameval,":fathernameval":fathernameval,":mothernameval":mothernameval,":mobileval":mobileval,":emailval":emailval,":addressval":addressval,":matval":matval,":sensecval":sensecval,":coursedetval":coursedetval,":departval":departval})
        con.commit()
        messagebox.showinfo("Registration Form","Form Submmitted Successfully...👍")
    cur.close()
    con.close()
    '''efname.delete()
    elname.delete()
    efathername.delete()
    emothername.delete()
    emobileno.delete()
    emailid.delete()
    eaddress.delete()
    emat.delete()
    sendata.delete()
    courses.delete()
    dep.delete()'''
ro = Tk()
ro.config(bg="white")
width1 = ro.winfo_screenwidth()
height1 = ro.winfo_screenheight()
ro.geometry("%dx%d+0+0"%(width1,height1))
ro.title("Registration Form")
#Frame 1
f1 = Frame(ro)
L1 = Label(f1,text="Registration Form",font="times_romans 40 bold",fg="red",bg="white")
L1.config(anchor=CENTER)
L1.pack()
f1.pack()
#Frame 2
f2 = Frame(ro,bg="#808080")
fname = StringVar()
lname = StringVar()
fathername = StringVar()
mothername = StringVar()
Mobile = StringVar()
email = StringVar()
Add = StringVar()
l1 = Label(f2,text="First Name:",fg="white",bg="#808080",font="times_roman 15 bold").grid(row=0,column=0,padx=10,pady=10,sticky="w")
l2 = Label(f2,text="Last Name:",fg="white",bg="#808080",font="times_roman 15 bold").grid(row=1,column=0,padx=10,pady=10,sticky="w")
l3 = Label(f2,text="Father's Name:",fg="white",bg="#808080",font="times_roman 15 bold").grid(row=2,column=0,padx=10,pady=10,sticky="w")
l4 = Label(f2,text="Mother's Name:",fg="white",bg="#808080",font="times_roman 15 bold").grid(row=3,column=0,padx=10,pady=10,sticky="w")
l5 = Label(f2,text="Mobile No.:",fg="white",bg="#808080",font="times_roman 15 bold").grid(row=4,column=0,padx=10,pady=10,sticky="w")
l6 = Label(f2,text="Email ID:",fg="white",bg="#808080",font="times_roman 15 bold").grid(row=5,column=0,padx=10,pady=10,sticky="w")
l4 = Label(f2,text="Address:",fg="white",bg="#808080",font="times_roman 15 bold").grid(row=6,column=0,padx=10,pady=10,sticky="w")
efname = Entry(f2,textvariable=fname,font="times_roman 15 bold").grid(row=0,column=1,padx=10,pady=10,sticky="w")
elname = Entry(f2,textvariable=lname,font="times_roman 15 bold").grid(row=1,column=1,padx=10,pady=10,sticky="w")
efathername = Entry(f2,textvariable=fathername,font="times_roman 15 bold").grid(row=2,column=1,padx=10,pady=10,sticky="w")
emothername = Entry(f2,textvariable=mothername,font="times_roman 15 bold").grid(row=3,column=1,padx=10,pady=10,sticky="w")
emobileno = Entry(f2,textvariable=Mobile,font="times_roman 15 bold").grid(row=4,column=1,padx=10,pady=10,sticky="w")
emailid = Entry(f2,textvariable=email,font="times_roman 15 bold").grid(row=5,column=1,padx=10,pady=10,sticky="w")
eaddress = Entry(f2,textvariable=Add,font="times_roman 15 bold").grid(row=6,column=1,padx=10,pady=10,sticky="w")
matricagg = StringVar()
sen_secc = StringVar()
coursedet = StringVar()
depart = StringVar()
l1 = Label(f2,text="Matric Aggregate's:",fg="white",bg="#808080",font="times_roman 15 bold").grid(row=7,column=0,padx=10,pady=10,sticky="w")
l2 = Label(f2,text="Sen_Sec:",fg="white",bg="#808080",font="times_roman 15 bold").grid(row=8,column=0,padx=10,pady=10,sticky="w")
l3 = Label(f2,text="Course:",fg="white",bg="#808080",font="times_roman 15 bold").grid(row=9,column=0,padx=10,pady=10,sticky="w")
l4 = Label(f2,text="Department:",fg="white",bg="#808080",font="times_roman 15 bold").grid(row=10,column=0,padx=10,pady=10,sticky="w")
emat = Entry(f2,textvariable=matricagg,font="times_roman 15 bold").grid(row=7,column=1,padx=10,pady=10,sticky="w")
sendata = Entry(f2,textvariable=sen_secc,font="times_roman 15 bold").grid(row=8,column=1,padx=10,pady=10,sticky="w")
courses = Entry(f2,textvariable=coursedet,font="times_roman 15 bold").grid(row=9,column=1,padx=10,pady=10,sticky="w")
dep = Entry(f2,textvariable=depart,font="times_roman 15 bold").grid(row=10,column=1,padx=10,pady=10,sticky="w")
f2.pack()

# Frame 3

f3=Frame(ro,bg="white")
b1 = Button(f3,text="Submit",bg="#808080",command=sub,fg="white",borderwidth=3).grid(row=0,column=0,padx=10,pady=10)
b2 = Button(f3,text="Cancel",bg="#808080",fg="white",borderwidth=3,command=cancel1).grid(row=0,column=1,padx=10,pady=10)
f3.pack()
ro.mainloop()